define({
  root: {
    _widgetLabel: "Draw",
    selectDrawMode: "Select drawing mode",
    clear: "Clear",
    point: "Point",
    line: "Line",
    polyline: "Polyline",
    freehandPolyline: "Freehand Polyline",
    triangle: "Triangle",
    extent: "Envelope",
    circle: "Circle",
    ellipse: "Ellipse",
    polygon: "Polygon",
    freehandPolygon: "Freehand Polygon",
    text:"Text",
    style:"Style",
    alpha:"Transparency",
    width:"Width",
    size:"Size",
    color:"Color",
    markerColor:"Marker Color",
    outlineColor:"Outline Color",
    lineColor:"Line Color",
    fillColor:"Fill Color",
    showMeasurements:"Show Measurements",
    areaUnits:"Area Units",
    distanceUnits:"Distance Units",
    kilometers:"Kilometers",
    miles:"Miles",
    meters:"Meters",
    feet:"Feet",
    yards:"Yards",
    squareKilometers:"Square kilometers",
    squareMiles:"Square miles",
    acres:"Acres",
    hectares:"Hectares",
    squareMeters:"Square meters",
    squareFeet:"Square feet",
    squareYards:"Square yards"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});