define({
  root: {
    enableUndoRedo: "Enable Undo/Redo",
    toolbarVisible: "Toolbar Visible",
    toolbarOptions: "Toolbar Options",
    mergeVisible: "Merge",
    cutVisible: "Cut",
    reshapeVisible: "Reshape",
    back: "Back",
    label: "Layer",
    edit: "Editable",
    update: "Disable Update Geometry",
    fields: "Fields",
    actions: "Actions",
    editpageName: "Name",
    editpageAlias: "Alias",
    editpageVisible: "Visible",
    editpageEditable: "Editable",
    noLayers: "No editable feature layers available"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});