define({
  root: {
    _widgetLabel: 'Chart',
    executeChartTip: 'Click one of the following task items to execute chart.',
    invalidConfig: 'Invalid configuration.',
    noneChartTip: 'There is no pre-configured chart tasks available.',
    chartParams: 'Options',
    charts: 'CHARTS',
    apply: 'APPLY',
    useSpatialFilter: 'Use spatial filter to limit features',
    useCurrentMapExtent: 'Only features touching the current map extent',
    drawGraphicOnMap: 'Only features touching a user defined area',
    chartResults: 'Chart Results',
    clearResults: 'Clear Results',
    noPermissionsMsg: 'You do not have permissions to access this service.',
    specifySpatialFilterMsg: 'Please specify spatial filter for this task.',
    queryError: 'Query failed.',
    noResults: "No feature found.",
    category: "Category",
    count: "Count",
    label: "Label"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});