//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/request dojo/Deferred dojo/promise/all dojo/json ./ConfigNode ./Category".split(" "),function(l,m,f,q,r,s,n,p,h){return l([],{categorys:null,displayCategorys:null,constructor:function(a,b,d){this.categorys=[];this.displayCategorys=[];this.initCategorys(b,a);this.deserialize(d,a)},initCategorys:function(a,b){var d=new h(b,"Attribute","Attribute",["app"],"app_theme app_map app_widgetOnScreen app_widgetPool app_splashPage app_portalUrl app_appId app_widgetManifestsMerged".split(" "),
["app_title","app_subtitle"]);this.categorys.push(d);var e=new h(b,"Theme","Theme",["app_theme"],["app_theme_name","app_theme_layout"]);this.categorys.push(e);e=new h(b,"Map","Map",["app_map"],["app_map_id","app_map_2D","app_map_3D"],[]);this.categorys.push(e);e=new h(b,"PreloadwidgetPanel","ScreenWidget Panel",["app_widgetOnScreen_panel"],["app_widgetOnScreen_panel_uri"]);this.categorys.push(e);e=new h(b,"WidgetpoolPanel","WidgetPool Panel",["app_widgetPool_panel"],["app_widgetPool_panel_uri"]);
this.categorys.push(e);f.forEach(a.widgetOnScreen.widgets,function(a,d){var e="ScreenWidget_"+a.id,c="app_widgetOnScreen_widgets["+d+"]",f=[c],c=[c+"_uri",c+"_id",c+"_name",c+"_index"];a.uri&&this.categorys.push(new h(b,e,a.label+" widget",f,c))},this);f.forEach(a.widgetOnScreen.groups,function(a,d){var e="ScreenWidgetGroup_"+a.id,c="app_widgetOnScreen_groups["+d+"]",k=[c],g=[c+"_id",c+"_index"];f.forEach(a.widgets,function(a,b){g.push(c+"_widgets["+b+"]_url");g.push(c+"_widgets["+b+"]__id");g.push(c+
"_widgets["+b+"]_uri");g.push(c+"_widgets["+b+"]_id");g.push(c+"_widgets["+b+"]_name");g.push(c+"_widgets["+b+"]_index")});this.categorys.push(new h(b,e,a.label,k,g))},this);f.forEach(a.widgetPool.widgets,function(a,d){var e="widgetPoolWidget_"+a.id,c="app_widgetPool_widgets["+d+"]",f=[c],c=[c+"_uri",c+"_id",c+"_name",c+"_index"];a.uri&&this.categorys.push(new h(b,e,a.label+" widget",f,c))},this);f.forEach(a.widgetPool.groups,function(a,d){var e="widgetPoolGroup_"+a.id,c="app_widgetPool_groups["+
d+"]",k=[c],g=[c+"_id",c+"_index"];f.forEach(a.widgets,function(a,b){g.push(c+"_widgets["+b+"]_url");g.push(c+"_widgets["+b+"]__id");g.push(c+"_widgets["+b+"]_uri");g.push(c+"_widgets["+b+"]_id");g.push(c+"_widgets["+b+"]_name");g.push(c+"_widgets["+b+"]_index")});this.categorys.push(new h(b,e,a.label,k,g))},this);this.displayCategorys.push(d)},getCategoryByName:function(a){return this.categorys[this.findCategory(a)]},getCategoryByField:function(a){var b;for(b=0;b<this.categorys.length;b++)if(this.categorys[b].hasField(a))return this.categorys[b];
return null},findCategory:function(a){return this._find(a,this.categorys)},findDisplayCategory:function(a){return this._find(a,this.displayCategorys)},_find:function(a,b){var d;for(d=0;d<b.length&&b[d].name!==a;d++);return d===b.length?-1:d},addCategoryToDisplay:function(a){-1===this.findDisplayCategory(a.name)&&this.displayCategorys.push(a)},removeCategoryFromDisplay:function(a){a=this.findDisplayCategory(a.name);0<=a&&this.displayCategorys.splice(a,1)},moveup:function(a){var b;a=this.findDisplayCategory(a.name);
return 0<a?(b=this.displayCategorys[a],this.displayCategorys[a]=this.displayCategorys[a-1],this.displayCategorys[a-1]=b,!0):!1},movedown:function(a){var b;a=this.findDisplayCategory(a.name);return 0<=a&&a<this.displayCategorys.length-1?(b=this.displayCategorys[a],this.displayCategorys[a]=this.displayCategorys[a+1],this.displayCategorys[a+1]=b,!0):!1},getTemplateJson:function(a){var b={configurationSettings:[],values:{}};f.forEach(this.displayCategorys,function(d,e){var h={category:d.title,fields:[]};
"fullJson"===a&&(h.categoryName=d.name);f.forEach(d.displayFields,function(d,e){var c=m.clone(d.fieldJson);(!a||"fullJson"!==a)&&delete c.id;h.fields[e]=c;b.values[c.fieldName]=p.getDefaultValue(d.fieldPath)},this);b.configurationSettings[e]=h},this);return b},deserialize:function(a,b){a&&(f.forEach(this.displayCategorys,function(a){a.displayFields=[]}),this.displayCategorys=[],a=n.parse(a),f.forEach(a.configurationSettings,function(a){var e=this.getCategoryByName(a.categoryName),f=0;e&&(f=e.deserialize(a.fields,
b),0<f&&this.displayCategorys.push(e))},this))}})});