//>>built
define(["dojo/_base/declare","dojo/_base/lang","dojo/_base/array"],function(l,m,h){var k={},f=l([],{id:null,parentNode:null,keyString:null,absolutePath:null,childs:null,nodeType:null,templateField:null,jsonObject:null,level:null,label:null,isVisible:!1,constructor:function(a,c,b,d,e){var g;this.parentNode=c;this.keyString=b;this.childs=[];this.absolutePath=""===d?b:d+"_"+b;this.jsonObject=a;this.level=e;this.initId();this.initLabel();this.initTemplateField(a);if("object"!==typeof a||null===a)this.nodeType=
"leaf";else if(m.isArray(a)){this.nodeType="array";for(c=0;c<a.length;c++)this.addChild(a[c],this.keyString+"["+c+"]",d,e)}else{this.nodeType="normal";for(g in a)a.hasOwnProperty(g)&&"config"!==g&&this.addChild(a[g],g,this.absolutePath,e);-1!==this.absolutePath.search(/widgets\[[0-9]+\]$/)&&(a.config=null,this.addChild(a.config,"config",this.absolutePath,e).nodeType="normal")}},initId:function(){var a,c;a=this.absolutePath.search(/_widgets\[[0-9]+\]/);c=this.absolutePath.search(/_groups\[[0-9]+\]/);
-1!==a||-1!==c?-1!==this.absolutePath.search(/_widgets\[[0-9]+\]$/)||-1!==this.absolutePath.search(/_groups\[[0-9]+\]$/)?this.id=this.parentNode.id+"_"+this.jsonObject.id:-1!==a?this.id=this.parentNode.id+"_"+this.keyString:-1!==c&&(this.id=this.parentNode.id+"_"+this.keyString):this.id=this.absolutePath;this.id=this.id.replace(/\[|\]/g,"-");this.id=this.id.replace(/\//g,"-")},initLabel:function(){this.label=this.keyString;if(-1!==this.absolutePath.search(/widgets\[[0-9]+\]$/)||-1!==this.absolutePath.search(/groups\[[0-9]+\]$/))this.label=
this.jsonObject.label},initTemplateField:function(a){this.templateField=f.getDefaultTemplateField(this.absolutePath,typeof a,this.label);f.setDefaultValue(this.absolutePath,a)},getTemplateFieldDefaultValue:function(){return this.templateField.defaultValue},getTemplateField:function(){var a={type:this.templateField.type,fieldName:this.templateField.fieldName,label:this.templateField.label,tooltip:this.templateField.tooltip};"leaf"!==this.nodeType&&(a.fieldName+="--");switch(a.type){case "string":a.stringFieldOption=
this.templateField.stringFieldOption;a.placeHolder=this.templateField.placeHolder;break;case "number":a.constraints=this.templateField.constraints;break;case "options":a.options=this.templateField.options}a.id=this.id;return a},setTemplateField:function(a){this.templateField.type=a.type;this.templateField.label=a.label;this.templateField.tooltip=a.tooltip;"leaf"!==this.nodeType&&(this.templateField.fieldName=this.templateField.fieldName.slice(0,this.templateField.fieldName.length-2));switch(this.templateField.type){case "string":this.templateField.stringFieldOption=
a.stringFieldOption;this.templateField.placeHolder=a.placeHolder;break;case "number":this.templateField.constraints=a.constraints;break;case "options":this.templateField.options=a.options}return a},addChild:function(a,c,b,d){a=new f(a,this,c,b,d+1);this.childs.push(a);return a},isLeaf:function(){var a=!1;this.childs&&0<this.childs.length&&(a=!0);return a},findNode:function(a){var c=[],b,d,e;a.split("_").forEach(function(a){var b=a.search(/\[[0-9]+\]/);-1!==b&&c.push(a.slice(0,b));c.push(a)});d=this;
if(d.keyString!==c[0])return null;for(a=1;a<c.length;a++){e=d.childs.length;for(b=0;b<e;b++)if(d.childs[b].keyString===c[a]){d=d.childs[b];break}if(b===e)return null}return d},setVisible:function(){for(var a=this;a;)a.isVisible=!0,a=a.parentNode},findNodeById:function(a){var c=null;this.traversal(this,function(){},function(b){return b.id===a?(c=b,!0):!1});return c},deserialize:function(a){a&&h.forEach(a.configurationSettings,function(a){h.forEach(a.fields,function(a){this.findNode(a.fieldName).setTemplateField(a)},
this)},this)}});f.getDefaultValue=function(a){return k[a]};f.setDefaultValue=function(a,c){var b;b=c;"app_portalUrl"===a||"app_map_itemId"===a?b=null:"object"===typeof c&&(b=!1);k[a]=b};f.getDefaultTemplateField=function(a,c,b){var d="string";switch(c){case "number":d="number";break;case "boolean":d="boolean";break;case "object":d="boolean",b="disable"}return{type:d,fieldName:a,label:b,tooltip:"",stringFieldOption:"textbox",placeHolder:b,constraints:{min:0,max:100,places:0},options:[{label:"label1",
value:"value1"},{label:"label2",value:"value2"}]}};return f});