define({
  root: {
    _widgetLabel: "Geoprocessing",
    execute: "Execute",
    help: "Help",
    input: "Input",
    output: "Output",
    executing: "Executing",
    requiredInfo: "is required.",
    drawnOnMap: "The result is drawn on the map.",
    clear: "Clear"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});