define({
  root: {
    labelTrackName: "Track Name",
    labelCreateTrack: " + Create a new track",
    labelCancel: "Cancel",
    labelSave: "Save",
    labelFinish: "Save & Close",
    labelPlay: "Play",
    labelEdit: "Edit",
    labelDownload: "Download",
    labelDrop: "Drop",
    tipNameExist: "Track name exist.",
    tipSaved: "saved.",
    tipSave: "Have unsaved data. Do you want to save?",
    tipCapture: "Press SPACE to capture a new View",
    tipInputName: "Please input name",
    tipDropTrack: "Drop this Track?"
  },
  "ar": true,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": true,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});