define({
  root: {
    taskUrl: "Task URL",
    serviceURLPlaceholder: "Please input Geoprocessing task URL",
    ok: "OK",
    cancel: "Cancel",
    layer: "Layer",
    action: "Action",
    input: "Input",
    output: "Output",
    name: "Name",
    type: "Type",
    required: "Required",
    layerOrder: "Layer order",
    options: "Options",
    defaultValue: "Default Value",
    inputFeatureBy: "Input Feature by",
    renderer: "Renderer",
    displayType: "Display type",
    label: "Label",
    tooltip: "Tooltip",
    visible: "Visible",
    helpUrl: "Help URL",
    useResultMapService: "Use the drawing options of result map service",
    drawOnMap: "Interactively drawing on the map",
    selectLayer: "Selecting a layer from the map",
    url: "URL",
    symbol: "Symbol",
    shareResults: "Add result as operational layer",
    popup: "Popup",
    setTask: "Set",
    setTaskTitle: "Set GP Task"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});