define({
    taskUrl: "Ülesande URL",
    serviceURLPlaceholder: "Sisestage geotöötluse ülesande URL",
    ok: "OK",
    cancel: "Tühista",
    layer: "Kiht",
    action: "Tegevus",
    input: "Sisend",
    output: "Väljund",
    name: "Nimi",
    type: "Tüüp",
    required: "Nõutav",
    layerOrder: "Kihi järjestus",
    options: "Valikud",
    defaultValue: "Vaikeväärtus",
    inputFeatureBy: "Sisendobjektid järgmise järgi",
    renderer: "Renderdaja",
    displayType: "Kuva tüüp",
    label: "Märgis",
    tooltip: "Kohtspikker",
    visible: "Nähtav",
    helpUrl: "Abi URL",
    useResultMapService: "Kasutage kaarditeenuse tulemuse joonistamisvalikuid",
    drawOnMap: "Joonistamine kaardile interaktiivselt",
    selectLayer: "Kaardilt kihi valimine",
    url: "URL",
    symbol: "Sümbol",
    shareResults: "Lisa tulemus töökihina",
    popup: "Hüpik",
    setTask: "Š_Set_ä",
    setTaskTitle: "Š_Set GP Task_ä"
});