define({
	root: {
    addDistance:"Add Length Unit",
    addArea:"Add Area Unit",
    label:"Label",
    abbr:"Abbreviation",
    conversion:"Conversion",
    actions:"Actions",
    areaUnits:"Area Units",
    distanceUnits:"Length Units",
    kilometers:"Kilometers",
    miles:"Miles",
    meters:"Meters",
    feet:"Feet",
    yards:"Yards",
    squareKilometers:"Square kilometers",
    squareMiles:"Square miles",
    acres:"Acres",
    hectares:"Hectares",
    squareMeters:"Square meters",
    squareFeet:"Square feet",
    squareYards:"Square yards",
    distance: "Distances",
    area: "Areas"
	},
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});