define({
  root: {
    routeUrl:"Route URL",
    locatorUrl:"Geocoder URL",
    geocoderOptions:"Geocoder options",
    autoComplete:"Auto complete",
    maxLocations:"Max locations",
    minCharacters:"Min characters",
    searchDelay:"Search delay",
    placeholder:"Placeholder",
    routeOptions:"Route options",
    directionsLanguage:"Directions language",
    directionsLengthUnits:"Directions length units",
    directionsOutputType:"Directions output type",
    impedanceAttribute:"Impedance attribute",
    kilometers: 'Kilometers',
    miles: 'Miles',
    meters: 'Meters',
    feet: 'Feet',
    yards: 'Yards',
    nauticalMiles:'Nautical Miles',
    parametersTip: 'Please set parameters correctly !'
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});