define({
  root: {
    add: "Click to Add a New Bookmark",
    title: "Title",
    placeholderBookmarkName: "Bookmark Name",
    ok: "OK",
    cancel: "Cancel",
    warning: "Please finish the edit!",
    edit: "Edit bookmark",
    errorNameExist: "Bookmark exists!",
    errorNameNull: "Invalid bookmark name!",
    addBookmark: "Create a New Bookmark",
    thumbnail: "Thumbnail",
    thumbnailHint: "Click image to update"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});