define({
  root: {
    serviceURL: "Service URL",
    defaultTitle: "Default Title",
    defaultAuthor: "Default Author",
    defaultCopyright: "Default Copyright",
    defaultFormat: "Default Format",
    defaultLayout: "Default Layout",
    warning: "Incorrect input",
    ok: "OK"
  },
  "ar": false,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": false,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});