define({
  root: {
    title: "Operational layers",
    labelLayer: "Layer Name",
    labelBoth: "Both",
    labelLeft: "L",
    labelRight: "R",
    labelUp: "U",
    labelDown: "D"
  },
  "ar": true,
  "cs": true,
  "da": true,
  "de": true,
  "es": true,
  "et": true,
  "fi": true,
  "fr": true,
  "he": true,
  "it": true,
  "ja": true,
  "ko": true,
  "lt": true,
  "lv": true,
  "nb": true,
  "nl": true,
  "pl": true,
  "pt-br": true,
  "pt-pt": true,
  "ro": true,
  "ru": true,
  "sv": true,
  "th": true,
  "tr": true,
  "zh-cn": true
});