//>>built
require({cache:{"url:builder/config/templates/AppWidgetsPage.html":'\x3cdiv class\x3d"app-widgets"\x3e\r\n  \x3cdiv class\x3d"preload-widgets-list" data-dojo-attach-point\x3d"preloadWidgetsNode"\x3e\r\n    \x3cdiv class\x3d"controller-widgets-list" data-dojo-attach-point\x3d"controllerWidgetsNode"\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"noncontroller-preload-widgets-list" data-dojo-attach-point\x3d"noncontrollerPreloadWidgetsNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"pool-widgets-list" data-dojo-attach-point\x3d"poolWidgetsNode"\x3e\r\n    \x3cdiv class\x3d"widgets-link" data-dojo-attach-point\x3d"backWidgetsNode" data-dojo-attach-event\x3d"onclick: _onBackWidgetsClick"\x3e \x26lt; \x26nbsp;\r\n      Widgets\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"widget-pool-title" data-dojo-attach-point\x3d"poolTitleNode"\x3e${nls.setControlledWidgetsBy}\x3cspan data-dojo-attach-point\x3d"controllerLabelNode"\x3e\x3c/span\x3e\x3c/div\x3e\r\n    \x3cdiv class\x3d"widget-pool-list" data-dojo-attach-point\x3d"poolWidgetsListNode"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/_base/array dojo/topic dojo/on dojo/mouse dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./templates/AppWidgetsPage.html ./WidgetsList ./MoveableNode ./WidgetSettingPage ./GroupSettingPage ./WidgetChoosePage ../utils jimu/utils jimu/PoolControllerMixin jimu/WidgetManager jimu/dijit/ViewStack jimu/dijit/Popup".split(" "),function(k,c,d,f,g,q,z,l,r,s,m,t,u,v,w,n,p,x,A,y,h){return k([l,r],{templateString:s,postCreate:function(){this.inherited(arguments);
this.widgetOnScreen=new m({name:"widgetOnScreen"},this.noncontrollerPreloadWidgetsNode);this.poolWidgets=new m({name:"poolWidgets"},this.poolWidgetsListNode);this.viewStack=new y({viewType:"dom",views:[this.preloadWidgetsNode,this.poolWidgetsNode]});this.viewStack.placeAt(this.domNode);this.poolControllerClass=k([l,x]);this.own(g.subscribe("editWidget",c.hitch(this,this._onEditWidget)));this.own(g.subscribe("chooseWidget",c.hitch(this,this._onChooseWidget)));this.own(g.subscribe("editGroup",c.hitch(this,
this._onEditGroup)))},postMixInProperties:function(){this.nls=c.mixin({},builderNls.common);this.nls=c.mixin(this.nls,builderNls.widgets)},startup:function(){this.inherited(arguments);this.viewStack.startup();this.widgetOnScreen.startup();this.poolWidgets.opened=!1;this.widgetOnScreen.opened=!0},destroy:function(){this.widgetOnScreen.destroy();this.poolWidgets.destroy();this.poolWidgets=this.widgetOnScreen=null;f.forEach(this.controllers,function(a){a.destroy()});this.controllers=[];this.inherited(arguments)},
setAppConfig:function(a){this.appConfig&&p.isEqual(this.appConfig.widgetOnScreen,a.widgetOnScreen)&&p.isEqual(this.appConfig.widgetPool,a.widgetPool)?this.appConfig=a:(a.visitElement(function(a){!a.widgets&&a.uri&&(a.icon&&(!a.icon.startWith("/")&&!a.icon.startWith("http")&&!a.icon.startWith("data"))&&(a.icon=n.getAppPathById(appId)+a.icon),a.config&&("string"===typeof a.config&&!a.config.startWith("/")&&!a.config.startWith("http"))&&(a.config=n.getAppPathById(appId)+a.config))}),this.appConfig=a,
this._createControllerWidgetNodes(),d.setStyle(this.noncontrollerPreloadWidgetsNode,{top:this.controllerWidgetsHeight+20+"px"}),this.widgetOnScreen.setSettings(this._getNonControllerPreloadWidgets()),this.widgetOnScreen.setAppConfig(this.appConfig),this.poolWidgets._started&&(0<this.controllers.length?this._initWidgetPool(this.controllers[0]):(this._initWidgetPool(null),this.viewStack.switchView(this.preloadWidgetsNode))),this.widgetChoosePage&&this.widgetChoosePage.setAppConfig(a),this.widgetSettingPage&&
this.widgetSettingPage.setAppConfig(a))},_getNonControllerPreloadWidgets:function(){var a=[];this.appConfig.visitElement(function(b,c,d,f){!b.isController&&f&&a.push(b)});return a},_createControllerWidgetNodes:function(){f.forEach(this.controllers,function(a){d.destroy(a.node);a.destroy()},this);this.controllers=[];f.forEach(this.appConfig.widgetOnScreen.widgets,function(a){a.isController&&this._createControllerWidgetNode(a)},this);this.controllerWidgetsHeight=118*this.controllers.length;d.setStyle(this.controllerWidgetsNode,
{height:this.controllerWidgetsHeight+"px"})},_createControllerWidgetNode:function(a){var b=d.create("div",{"class":"controller-widget"},this.controllerWidgetsNode),e=new t({type:"widget",w:74,h:118,setting:a,listName:"controllerWidgets",style:{left:"30px"}});d.place(e.domNode,b);e.startup();e=d.create("div",{"class":"action-node"},b);d.create("div",{"class":"action-text",innerHTML:this.nls.setControlledWidgets},e);d.create("div",{"class":"action-arrow",innerHTML:"\x3e"},e);a=new this.poolControllerClass(a);
a.appConfig=this.appConfig;a.node=b;this.controllers.push(a);this.own(q(e,"click",c.hitch(this,this._openWidgetPool,a)))},_openWidgetPool:function(a){!1!==a.visible&&(this.currentController=a,this.viewStack.switchView(this.poolWidgetsNode),this.poolWidgets.controller=a,this.poolWidgets.opened=!0,this.widgetOnScreen.opened=!1,this.controllerLabelNode.innerHTML=a.label,this._initWidgetPool(a),this.poolWidgets._started||this.poolWidgets.startup())},_initWidgetPool:function(a){this.poolWidgets.setSettings(a?
a.getAllConfigs():[]);this.poolWidgets.setAppConfig(this.appConfig)},_onBackWidgetsClick:function(){this._createControllerWidgetNodes();this.viewStack.switchView(this.preloadWidgetsNode);this.poolWidgets.opened=!1;this.widgetOnScreen.opened=!0},_onEditWidget:function(a){this.widgetSettingPage=new u({appConfig:this.appConfig},this.widgetSettingPageNode);this.widgetSettingPage.setting=c.clone(a);a=new h({titleLabel:this.nls.configLabel+" "+a.label,content:this.widgetSettingPage,container:"main-page",
buttons:[{label:this.nls.ok,onClick:c.hitch(this.widgetSettingPage,this.widgetSettingPage.onOk)},{label:this.nls.cancel,onClick:c.hitch(this.widgetSettingPage,this.widgetSettingPage.onCancel)}],onClose:c.hitch(this.widgetSettingPage,this.widgetSettingPage.onClose)});d.addClass(a.domNode,"widget-setting-popup");this.widgetSettingPage.startup()},_onChooseWidget:function(a,b){this.widgetChoosePage=new w({appConfig:this.appConfig},this.widgetChoosePageNode);this.widgetChoosePage.fromNode=a;this.widgetChoosePage.fromList=
b;new h({titleLabel:"Choose Widget",content:this.widgetChoosePage,container:"main-page",buttons:[{label:this.nls.ok,onClick:c.hitch(this.widgetChoosePage,this.widgetChoosePage.onOk)},{label:this.nls.cancel}]});this.widgetChoosePage.startup()},_onEditGroup:function(a,b){this.groupSettingPage=new v({setting:c.clone(b)});new h({titleLabel:b.label,content:this.groupSettingPage,container:"main-page",buttons:[{label:this.nls.ok,onClick:c.hitch(this.groupSettingPage,this.groupSettingPage.onOk)},{label:this.nls.cancel}]});
this.groupSettingPage.startup()},_getPopupSize:function(){var a=d.getContentBox("main-page"),b={};1024>=a.w?(b.width=a.w-20,b.height=a.h-20):(b.width=1024,b.height=768);return b}})});