//>>built
define("dojo/_base/declare dojo/_base/html dojo/_base/lang dojo/on dojo/Evented dojo/aspect dojo/mouse dojo/topic dojo/query ./Mover dojo/dnd/move dojo/mouse dojo/NodeList-dom dojo/NodeList-manipulate dijit/_WidgetBase jimu/dijit/Message".split(" "),function(k,a,c,d,l,g,f,e,m,n,p,r,s,t,q,h){return k([q,l],{type:"",label:"",isMoving:!1,isMouseDown:!1,postMixInProperties:function(){this.nls=c.mixin({},builderNls.common);this.nls=c.mixin(this.nls,builderNls.widgets)},postCreate:function(){this.inherited(arguments);
"addBtn"===this.type?(this.label="addBtn",this.createAddBtn()):"empty"===this.type?(this.label="empty",this.createEmptyNode()):("widget"===this.type?this.createWidgetNode():this.createGroupNode(),"poolWidgets"===this.listName&&(this.dnd=new p.boxConstrainedMoveable(this.domNode,{handle:this.boxNode,box:this.parentBox,within:!0,delay:5,mover:n}),this.bindMoveEvent()));a.addClass(this.domNode,"moveable");a.setStyle(this.domNode,{width:this.w+"px",height:this.h+"px"})},bindMoveEvent:function(){g.after(this.dnd,
"onMoveStart",c.hitch(this,function(){this.isMoving=!0}),!0);g.after(this.dnd,"onMoveStop",c.hitch(this,function(){this.isMoving=!1}),!0)},_createWidgetIconNode:function(){this.iconNode=a.create("img",{"class":"icon",src:this.setting.icon,style:{width:"40px",height:"40px",margin:(this.w-40)/2+"px"}},this.boxNode)},_createPlaceholderNode:function(){this.placeholderNode=a.create("div",{"class":"placehoder",style:{width:"40px",height:"40px",margin:(this.w-40)/2+"px"}},this.boxNode);a.create("div",{"class":"placehoder-inner",
innerHTML:this.setting.placeholderIndex,style:{width:"24px",height:"24px",lineHeight:"24px",borderRadius:"12px",margin:"7px"}},this.placeholderNode)},createWidgetNode:function(){a.addClass(this.domNode,"widget-node");this.boxNode=a.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);this.setting.uri?this._createWidgetIconNode():this._createPlaceholderNode();this.label=this.setting.label?this.setting.label:"Widget";this.name=this.setting.name?this.setting.name:"Widget";
this.labelNode=a.create("div",{"class":"label",innerHTML:this.label,title:this.label},this.domNode);!1===this.setting.visible&&a.addClass(this.domNode,"hide");this.own(d(this.boxNode,f.enter,c.hitch(this,function(){e.publish("actionTriggered",this.setting.id,"highLight");this.setting.uri&&(this.editNode=this._createEditNode(),this.own(d(this.editNode,"click",c.hitch(this,function(b){b.stopPropagation();e.publish("editWidget",this.setting)}))),!1===this.setting.inPanel?(this.switchNode=this._createSwitchNode(),
this.own(d(this.switchNode,"click",c.hitch(this,function(b){b.stopPropagation();!1===this.setting.visible?(this.setting.visible=!0,a.removeClass(this.domNode,"hide")):(this.setting.visible=!1,a.addClass(this.domNode,"hide"));e.publish("configChanged",this.setting.id,this.setting)})))):(this.dropNode=this._createDropNode(),this.own(d(this.dropNode,"click",c.hitch(this,function(b){b.stopPropagation();var d=new h({message:this.nls.dropWidgetMessage,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){"poolWidgets"!==
this.listName&&(this.setting.uri="",this.setting.label="Widget",this.setting.name=void 0,this.setting.placeholderIndex="?",this.setting.config=void 0,this.label="Widget",this.labelNode.innerHTML=this.label,a.destroy(this.iconNode),this._createPlaceholderNode());this.emit("removeNode");d.close()})},{label:this.nls.cancel}]})})))))})));this.own(d(this.boxNode,f.leave,c.hitch(this,function(){e.publish("actionTriggered",this.setting.id,"removeHighLight");this.editNode&&a.destroy(this.editNode);this.dropNode&&
a.destroy(this.dropNode);this.switchNode&&a.destroy(this.switchNode)})))},createGroupNode:function(){a.addClass(this.domNode,"group-node");this.boxNode=a.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);this.label=this.setting.label?this.setting.label:"Group";this.name=this.setting.name?this.setting.name:"Group";this.labelNode=a.create("div",{"class":"label",innerHTML:this.setting.label,title:this.setting.label},this.domNode);this._createSmallWidgets();this.own(d(this.boxNode,
f.enter,c.hitch(this,function(){e.publish("actionTriggered",this.setting.id,"highLight");this.editNode=this._createEditNode();this.own(d(this.editNode,"click",c.hitch(this,function(b){b.stopPropagation();e.publish("editGroup",this,this.setting)})));this.own(d(this.editNode,"mousedown",function(b){b.stopPropagation()}));this.own(d(this.editNode,"mouseup",function(b){b.stopPropagation()}));"poolWidgets"===this.listName&&(this.dropNode=this._createDropNode(),this.own(d(this.dropNode,"click",c.hitch(this,
function(b){var a=new h({message:this.nls.dropGroupMessage,buttons:[{label:this.nls.ok,onClick:c.hitch(this,function(){this.emit("removeNode");a.close()})},{label:this.nls.cancel}]});b.stopPropagation()}))),this.own(d(this.dropNode,"mousedown",function(b){b.stopPropagation()})),this.own(d(this.dropNode,"mouseup",function(b){b.stopPropagation()})))})));this.own(d(this.boxNode,f.leave,c.hitch(this,function(){e.publish("actionTriggered",this.setting.id,"removeHighLight");this.editNode&&a.destroy(this.editNode);
this.dropNode&&a.destroy(this.dropNode)})));this.own(d(this.boxNode,"click",c.hitch(this,function(b){b.preventDefault();b.stopPropagation();"open"===this.status?this.closeGroup():this.openGroup()})))},closeGroup:function(){this.status="close"},openGroup:function(){this.status="open"},createAddBtn:function(){a.addClass(this.domNode,"add-widget-node");var b=a.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode);a.create("img",{src:"builder/css/images/add_widget.png"},
b);a.create("div",{"class":"label",innerHTML:"Click here to add widget"},b)},createEmptyNode:function(){a.addClass(this.domNode,"empty-node");a.create("div",{"class":"box",style:{width:this.w+"px",height:this.w+"px"}},this.domNode)},_createEditNode:function(){return a.create("div",{"class":"edit-btn",style:{right:"4px",bottom:"4px",width:"25px",height:"25px"}},this.boxNode)},_createDropNode:function(){return a.create("div",{"class":"drop-btn",style:{right:"3px",top:"3px",width:"10px",height:"10px"}},
this.boxNode)},_createSwitchNode:function(){return a.create("div",{"class":"switch-btn",style:{right:"3px",top:"3px",width:"15px",height:"10px"}},this.boxNode)},_createSmallWidgets:function(){m(".small",this.boxNode).remove();var b=[],a=!1;4<this.setting.widgets.length?(b=this.setting.widgets.slice(0,3),a=!0):(b=this.setting.widgets,a=!1);b.forEach(c.hitch(this,function(a){this._createSmallWidget(a)}));a&&this._createSmallMore()},_createSmallWidget:function(b){var c;c=a.create("div",{"class":"small small-widget",
"data-wid":b.id,style:{width:"20px",height:"20px",marginLeft:(this.w-40)/3+"px",marginTop:(this.w-40)/3+"px"}},this.boxNode);a.create("img",{src:b.icon,style:{width:"20px",height:"20px"}},c);return c},_createSmallMore:function(){var b;b=a.create("div",{"class":"small small-more",style:{width:"20px",height:"20px",marginLeft:(this.w-40)/3+"px",marginTop:(this.w-40)/3+"px"}},this.boxNode);a.create("img",{src:"builder/images/more_widget.png",style:{width:"20px"}},b);return b},addWidget:function(a){"group"===
this.type&&(this.setting.widgets.push(a.setting),this._createSmallWidgets())},updateSmallWidgets:function(){this._createSmallWidgets()},destroy:function(){this.margin&&this.margin.destroy();this.inherited(arguments)}})});