//>>built
require({cache:{"url:builder/config/templates/ThemeConfig.html":'\x3cdiv class\x3d"theme-config"\x3e\r\n  \x3cdiv class\x3d"theme-list" data-dojo-attach-point\x3d"themeList"\x3e\r\n    \x3cdiv class\x3d"theme-title"\x3e\x3c/div\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"style-list" data-dojo-attach-point\x3d"styleList"\x3e\r\n    \x3c!--div class\x3d"style-text"\x3e${nls.styleTitle}\x3c/div--\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv class\x3d"layout-list" data-dojo-attach-point\x3d"layoutList"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"theme-loading-cover" style\x3d"display:none" data-dojo-attach-point\x3d"themeCoverNode"\x3e\x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dojo/_base/lang dojo/_base/html dojo/topic dojo/on dojo/aspect dojo/mouse dojo/query dojo/NodeList-dom dijit/_WidgetBase dijit/_TemplatedMixin dojo/text!./templates/ThemeConfig.html dojo/dom-construct dojo/dom-class dojo/dom-style dojo/dom-attr dojo/_base/array dojo/Deferred dojo/request dojo/dom jimu/utils ./ThemeManager ../serviceUtils".split(" "),function(r,f,e,l,n,z,A,B,C,s,t,u,d,D,v,E,m,p,F,w,G,x,y){return r([s,t],{templateString:u,themeLoadDef:void 0,constructor:function(){},
postMixInProperties:function(){this.nls=builderNls.themes},startup:function(){this.inherited(arguments);this.themeManager=new x;this.themeLoadDef=this.themeManager.loadThemes();this.themeLoadDef.then(f.hitch(this,function(a){this.initThemePage(a)}))},initThemePage:function(a){var b,c,g,h,k,q;m.forEach(a,function(a){k=e.create("div",{"class":"catalog-theme-content-div"},this.themeList);b=e.create("div",{"class":"catalog-theme-div"},k);e.create("div",{"class":"catalog-theme-name-div",innerHTML:a.getLabel()},
k);q=e.create("div",{"class":"catalog-theme-img-div"},b);d.create("img",{src:a.getIcon(),"class":"catalog-theme-img"},q);c=d.create("div",{"class":"theme-cl-selected-div"},b);d.create("img",{"class":"theme-cl-selected-img",src:"builder/css/images/check.png"},c);n(b,"click",f.hitch(this,this._onStartChangeTheme,a.getName()));g=d.create("div",{"class":""},this.styleList);this.initStyle(a,g);h=d.create("div",{"class":""},this.layoutList);this.initLayout(a,h);a.domNodes.theme=b;a.domNodes.themeSL=c;a.domNodes.styleList=
g;a.domNodes.layoutList=h},this)},initStyle:function(a,b){var c,g,h,k;c=d.create("div",{"class":"style-section"},b);d.create("div",{innerHTML:this.nls.styleTitle,"class":"style-text"},c);k=d.create("div",{"class":"style-color-content"},c);m.forEach(a.getStyles(),function(a){g=d.create("div",{"class":"style-div"},k);v.set(g,"backgroundColor",a.styleColor);a.domNode=g;n(g,"click",f.hitch(this,this._onStyleChanged,a.name));h=d.create("div",{"class":"style-selected-div"},g);d.create("img",{"class":"style-selected-img",
src:"builder/css/images/check.png"},h);a.selectedNode=h},this);e.setStyle(b,"display","none")},initLayout:function(a,b){var c;c=d.create("div",{"class":"layout-section",id:a.getName()+"-layout-section"},b);d.create("div",{innerHTML:this.nls.layoutTitle,"class":"layout-text"},c);m.forEach(a.getLayouts(),function(b){this._drawLayout(a,b,c)},this);e.setStyle(b,"display","none")},_drawLayout:function(a,b,c){b.domClass||(b.domClass=" ");c=d.create("div",{"class":"layout-div "+b.domClass,title:b.name},
c);a=b.icon?a.getUrl()+b.icon:"builder/css/images/current_layout.png";d.create("img",{"class":"layout-image",src:a},c);b.domNode=c;n(c,"click",f.hitch(this,this._onLayoutChanged,b.name));a=d.create("div",{"class":"layout-selected-div"},c);d.create("img",{"class":"layout-selected-img",src:"builder/css/images/check.png"},a);b.selectedNode=a},_onStyleChanged:function(a){this.changeStyle(a,null,!0)},_onLayoutChanged:function(a){this.changeLayout(a,null,!0)},_onStartChangeTheme:function(a){this.changeTheme(a,
!0)},changeStyle:function(a,b,c){b||(b=this.themeManager.getCurrentTheme());b.currentStyleName!==a&&(b.currentStyleName&&e.removeClass(b.getCurrentStyle().domNode,"style-selected"),b.changeCurrentStyle(a),e.addClass(b.getCurrentStyle().domNode,"style-selected"),c&&l.publish("styleChanged",f.clone(b.getCurrentStyle())))},changeLayout:function(a,b,c){b||(b=this.themeManager.getCurrentTheme());b.currentLayoutName!==a&&(b.currentLayoutName&&e.removeClass(b.getCurrentLayout().domNode,"layout-selected"),
b.changeCurrentLayout(a),e.addClass(b.getCurrentLayout().domNode,"layout-selected"),c&&l.publish("layoutChanged",f.clone(b.getCurrentLayout())))},_copyThemeFromRepo:function(a){var b=new p,c=this.themeManager.getThemeByName(a);c.loadLayouts().then(f.hitch(this,function(){var e=c.getLayoutByName("default");y.copyThemeToApp(appId,a,c.appConfig?c.appConfig.getCleanConfig():e.layoutConfig).then(f.hitch(this,function(a){a.success?b.resolve():b.reject()}),function(a){b.reject(a)})}));return b},changeTheme:function(a,
b){var c=new p;this.themeManager.currentThemeName!==a?(l.publish("startChangeTheme"),this._copyThemeFromRepo(a).then(f.hitch(this,function(){this.themeManager.currentThemeName&&(e.removeClass(this.themeManager.getCurrentTheme().domNodes.theme,"catalog-theme-selected"),e.setStyle(this.themeManager.getCurrentTheme().domNodes.styleList,"display","none"),e.setStyle(this.themeManager.getCurrentTheme().domNodes.layoutList,"display","none"));this.themeManager.changeCurrentTheme(a);b&&l.publish("themeChanged",
f.clone(this.themeManager.getCurrentTheme()));e.addClass(this.themeManager.getCurrentTheme().domNodes.theme,"catalog-theme-selected");e.setStyle(this.themeManager.getCurrentTheme().domNodes.styleList,"display","block");e.setStyle(this.themeManager.getCurrentTheme().domNodes.layoutList,"display","block");c.resolve()}))):c.resolve();return c},setAppConfig:function(a,b){var c,d;this.themeLoadDef.then(f.hitch(this,function(){b?(m.forEach(this.themeManager.themes,function(a){this.changeStyle("default",
a,!1);this.changeLayout("default",a,!1);a.clear()},this),this.changeTheme(a.theme.name,!1).then(f.hitch(this,function(){a.theme.styles&&a.theme.styles[0]&&this.changeStyle(a.theme.styles[0],this.themeManager.getCurrentTheme(),!1);c=w.byId(this.themeManager.getCurrentTheme().getName()+"-layout-section");d=this.themeManager.getCurrentTheme().getLayoutByCompare(a.getCleanConfig());d||(d=this.themeManager.getCurrentTheme().addLayout("appLayout",a.getCleanConfig(),"app-layout"),this._drawLayout(this.themeManager.getCurrentTheme(),
d,c));this.changeLayout(d.name,this.themeManager.getCurrentTheme(),!1);this.themeManager.getCurrentTheme().setAppConfig(a);e.setStyle(this.themeList,"display","block")}))):this.themeManager.getCurrentTheme()&&this.themeManager.getCurrentTheme().setAppConfig(a)}))}})});