//>>built
define("dojo/_base/lang dojo/cookie dojo/i18n dojo/request/xhr dojo/Deferred dojo/json dojo/_base/array esri/request jimu/utils jimu/portalUrlUtils builder/portalUtils dojo/promise/all".split(" "),function(q,z,r,g,f,n,l,A,w,k,h,p){function s(a,b,c,d,e,m){b.portalUrl=c;m&&(b.appId=m);b.map.itemId=d;b.geometryService=e.helperServices.geometry.url;a.webmap||(b.map.mapOptions||(b.map.mapOptions={}),b.map.mapOptions.extent=e.defaultExtent);b.httpProxy=window.isXT?{useProxy:!0,url:"/proxy.js"}:{useProxy:!0,
url:b.portalUrl+"sharing/proxy"}}function t(a,b){var c=new f,d={title:a.name,type:"Web Mapping Application",typeKeywords:"Web AppBuilder",text:n.stringify(b),snippet:a.description,tags:a.tags};h.getPortal(k.getPortalUrlFromLocation()).getUser().then(function(b){a.folderId===b.username&&(a.folderId="");b.addItem(d,a.folderId).then(function(d){d.success?(d.user=b,b.addItem({title:a.name,type:"Code Attachment",typeKeywords:"Code, Web Mapping Application, Javascript",relationshipType:"WMA2Code",originItemId:d.id,
url:k.getItemUrl(k.getPortalUrlFromLocation(),d.id)+"/package"},a.folderId).then(function(a){c.resolve(d)},function(a){c.resolve(d)})):c.resolve(d)},function(a){c.reject(a)})},function(a){c.reject(a)});return c}function u(a){var b=new f;g("stemapp/"+a+"/list.json",{preventCache:!0,handleAs:"json"}).then(function(c){var d=[];l.forEach(c[a],function(b){d.push(g("stemapp/"+a+"/"+b+"/manifest.json",{preventCache:!0,handleAs:"json"}))});p(d).then(function(c){l.forEach(c,function(b){b.url="stemapp/"+a+
"/"+b.name+"/";b.icon=b.url+"images/icon.png";"themes"===a?x(b):y(b);b.i18nLabels={};if(!(b.properties&&!1===b.properties.hasLocale)){var c=path+"stemapp/"+a+"/"+b.name,d="themes"===a?"_themeLabel":"_widgetLabel",e=q.mixin({},r.getLocalization(c,"strings","abcd")),e=w.merge(e,q.mixin({},r.getLocalization(c,"strings",window.builderNls._locale)));b.i18nLabels[window.builderNls._locale]=e[d]}});b.resolve({success:!0,manifests:c})})},function(a){b.reject({success:!1,message:a.message})});return b}function x(a){a.panels.forEach(function(a){a.uri=
"panels/"+a.name+"/Panel.js"});a.styles.forEach(function(a){a.uri="styles/"+a.name+"/style.css"});a.layouts.forEach(function(a){a.uri="layouts/"+a.name+"/config.json";a.icon="layouts/"+a.name+"/icon.png"})}function y(a){"undefined"!==typeof a["2D"]&&(a.support2D=a["2D"]);"undefined"!==typeof a["3D"]&&(a.support3D=a["3D"]);"undefined"===typeof a["2D"]&&"undefined"===typeof a["3D"]&&(a.support2D=!0);delete a["2D"];delete a["3D"];"undefined"===typeof a.properties&&(a.properties={});"inPanel hasLocale hasStyle hasConfig hasUIFile hasSettingPage hasSettingUIFile hasSettingLocale hasSettingStyle".split(" ").forEach(function(b){"undefined"===
typeof a.properties[b]&&(a.properties[b]=!0)});"undefined"===typeof a.properties.isController&&(a.properties.isController=!1)}var v={getAppList:function(){var a=new f,b;isXT?(b=h.getPortal(window.portalUrl),b.getUser().then(function(b){g("/builder/rest/apps/list/"+b.username,{preventCache:!0,handleAs:"json"}).then(function(b){a.resolve(b)},function(b){a.reject(b)})},function(b){a.reject(b)})):(b=k.getPortalUrlFromLocation(),(b=h.getPortal(b))?b.getUser().then(function(b){b.getItemsByKeywords("Web AppBuilder").then(function(b){var c=
[];(b=b&&b.results)&&0<b.length&&(c=l.map(b,function(a){return{name:a.title,description:a.description,id:a.id}}));a.resolve(c)},function(b){a.reject({success:!1,message:""})})},function(b){a.reject({success:!1,message:""})}):a.reject({success:!1,message:""}));return a},getAppInfo:function(a){if(isXT)return g("/builder/rest/apps/"+a,{preventCache:!0,handleAs:"json"});var b=new f;h.getPortal(k.getPortalUrlFromLocation()).getItemById(a).then(function(a){b.resolve({name:a.title,description:a.description,
id:a.id})});return b},updateApp:function(a){var b=new f;isXT?h.getPortal(window.portalUrl).getUser().then(function(c){g("/builder/rest/apps/updateapp",{handleAs:"json",method:"POST",data:{id:a.id,name:a.name,description:a.description,modified:c.username||"",creator:a.creator}}).then(function(a){b.resolve(a)},function(a){b.reject(a)})},function(a){b.reject(a)}):b.resolve({success:!0});return b},createApp:function(a){var b=new f,c,d=window.portalUrl,e=h.getPortal(d);c=e.loadSelfInfo();var m=e.getUser(),
e=null;a.webmap?(e=new f,e.resolve(a.webmap)):e=h.getDefaultWebMap(d);if(isXT){var l=g("/builder/rest/signininfo/getcurrentinfo",{handleAs:"json",preventCache:!0});c=[c,m,e,l];p(c).then(function(c){var e=c[1],f={map:{}};s(a,f,d,c[2],c[0],c[3].info.appId);g("/builder/rest/apps/createapp",{handleAs:"json",method:"POST",data:{name:a.name,description:a.description,is3D:a.is3D,creator:e.username||"",modified:e.username||"",extraPropertyOfAppConfig:JSON.stringify(f)}}).then(function(a){b.resolve(a)},function(a){b.reject(a)})},
function(a){b.reject({success:!1,message:builderNls.serviceUtils.createError})})}else m=v.getPredefinedAppConfig("true"===a.is3D?"default3DApp":"default2DApp"),c=[c,m,e],p(c).then(function(c){var e=c[1];s(a,e,d,c[2],c[0]);t(a,e).then(function(a){a.success?a.user.updateItem(a.id,{url:k.getDeployContextFromLocation()+"apps/webappviewer/index.html?id\x3d"+a.id}).then(function(c){b.resolve({success:!0,newAppId:a.id})},function(c){b.resolve({success:!0,newAppId:a.id})}):b.reject({success:!1,message:builderNls.serviceUtils.createError})},
function(a){b.reject({success:!1,message:builderNls.serviceUtils.createError})})},function(a){b.reject({success:!1,message:builderNls.serviceUtils.createError})});return b},duplicateApp:function(a,b){var c=new f;isXT?h.getPortal(window.portalUrl).getUser().then(function(b){g("/builder/rest/apps/duplicateapp",{handleAs:"json",method:"POST",data:{name:a.name,description:a.description,id:a.createFromId,is3D:a.is3D,creator:b.username||"",modified:b.username||""}}).then(function(a){c.resolve(a)},function(a){c.reject(a)})},
function(a){c.reject({message:builderNls.serviceUtils.createError})}):t(a,b).then(function(a){a.success?a.user.updateItem(a.id,{url:k.getDeployContextFromLocation()+"apps/webappviewer/index.html?id\x3d"+a.id}).then(function(b){c.resolve({success:!0,newAppId:a.id})},function(b){c.resolve({success:!0,newAppId:a.id})}):c.reject({success:!1,message:builderNls.serviceUtils.duplicateError})},function(a){c.reject({success:!1,message:builderNls.serviceUtils.duplicateError})});return c},saveApp:function(a,
b){var c=new f;isXT?h.getPortal(window.portalUrl).getUser().then(function(d){g("/builder/rest/apps/"+a+"/saveconfig",{data:{appConfig:n.stringify(b),modified:d.username},method:"POST",handleAs:"json"}).then(function(a){c.resolve(a)},function(a){c.reject(a)})},function(a){c.reject(a)}):h.getPortal(k.getPortalUrlFromLocation()).getUser().then(function(d){d.updateItem(a,{text:n.stringify(b)}).then(function(a){c.resolve({success:!0,newAppId:a.id})},function(a){c.reject({success:!1,message:a.message})})},
this,function(a){c.reject({success:!1,message:a.message})});return c},getPredefinedAppConfig:function(a){return g("builder/predefined-apps/"+a+"/config.json",{handleAs:"json"})},copyThemeToApp:function(a,b,c){if(isXT)return g("/builder/rest/apps/"+a+"/copytheme",{handleAs:"json",method:"POST",data:{themeName:b,layoutConfig:JSON.stringify(c)}});a=new f;a.resolve({success:!0});return a},copyWidgetToApp:function(a,b,c){if(isXT)return g.post("/builder/rest/apps/"+a+"/copywidget",{data:{widgetName:b,widgetLabel:c},
handleAs:"json"});a=new f;a.resolve({success:!0});return a},getAllThemes:function(){if(isXT)return g("/builder/rest/themes/getall",{handleAs:"json"});var a=new f;u("themes").then(function(b){a.resolve({success:!0,themes:b.manifests})},function(b){a.reject(b)});return a},searchWidgets:function(a){if(isXT)return g("/builder/rest/widgets/search?q\x3d"+JSON.stringify(a),{handleAs:"json"});var b=new f;u("widgets").then(function(c){var d=[];l.forEach(c.manifests,function(b){a["properties.inPanel"]===b.properties.inPanel&&
(a.support2D===b.support2D||a.support3D===b.support3D)&&d.push(b)});b.resolve({success:!0,widgets:d})},function(a){b.reject(a)});return b}};return v});